TWT233/khl.py

setup.cfg
=> build: v0.1.2

example/ex07_card_message/ex07.py, khl/card/__init__.py, khl/card/element.py, khl/card/interface.py, khl/card/module.py, khl/card/struct.py
结构体示例
```python
@bot.command()
async def test(msg: Message):
sec = Element.Paragraph(2, Fields('a'))
sec .append(Fields('b'))
sec.pop(1)
print(sec.len())
sec.append(Fields('c'))
card = Card(Module.Section(sec))
cm = CardMessage(card)
await msg.reply(cm)
```
~~虽然写的有点迷，但是能用~~
=> 补充Module.Container, 结构体

khl/bot/bot.py, khl/client.py
=> refactor: alter delete_channel() arg

khl/receiver.py
when ws conn already closed, the heartbeat coro is still heartbeating, which cause the error log: cannot write to closing transport
=> fix(receiver): heartbeat when conn already closed

khl/api.py
when building req under multipart/form-data type, the content-type should be delegated to aiohttp
but if simply pop content-type field from headers, the original headers is affected too, due to the ref pass
this commit introduces a set of functions to resolve this problem
=> fix(api): multipart/form-data req is handled incorrectly

khl/requester.py
=> fix(requester): wrong terminating in pagination

khl/api.py, khl/bot/bot.py, khl/client.py, khl/game.py
实现了 ``用户动态相关接口``
- [/api/v3/game/create](https://developer.kaiheila.cn/doc/http/game#%E6%B7%BB%E5%8A%A0%E6%B8%B8%E6%88%8F)
- [/api/v3/game/update](https://developer.kaiheila.cn/doc/http/game#%E6%9B%B4%E6%96%B0%E6%B8%B8%E6%88%8F)
- [/api/v3/game/delete](https://developer.kaiheila.cn/doc/http/game#%E5%88%A0%E9%99%A4%E6%B8%B8%E6%88%8F)
- [/api/v3/game/activity](https://developer.kaiheila.cn/doc/http/game#%E6%B7%BB%E5%8A%A0%E6%B8%B8%E6%88%8F%E8%AE%B0%E5%BD%95-%E5%BC%80%E5%A7%8B%E7%8E%A9)
- [/api/v3/game/delete-activity](https://developer.kaiheila.cn/doc/http/game#%E5%88%A0%E9%99%A4%E6%B8%B8%E6%88%8F%E8%AE%B0%E5%BD%95-%E7%BB%93%E6%9D%9F%E7%8E%A9)
=> 添加 Game 相关 API

khl/role.py
添加权限的对应掩码解析
在 ``Role`` 类的 ``has_permission`` 方法, 返回一个 ``bool``
``bitValue`` 值见 [权限说明](https://developer.kaiheila.cn/doc/http/guild-role#%E6%9D%83%E9%99%90%E8%AF%B4%E6%98%8E)
=> feature(role): add has_permission method

khl/command/lexer.py
fix(patch): Modify the commit message
=> feat(lexer): Modify the parameter cut logic to support space prefix( second )

khl/card/module.py
self._type is always 'countdown'
=> fix(Card): repair second countdown start time

khl/__init__.py, khl/api.py, khl/bot/bot.py, khl/channel.py, khl/client.py, khl/interface.py
doc: [channel/update](https://developer.kaiheila.cn/doc/http/channel#%E7%BC%96%E8%BE%91%E9%A2%91%E9%81%93)
=> implement `channel/update` api

khl/api.py, khl/guild.py
Implemented: [channel-user/get-joined-channel](https://developer.kaiheila.cn/doc/http/channel-user#%E6%A0%B9%E6%8D%AE%E7%94%A8%E6%88%B7id%E5%92%8C%E6%9C%8D%E5%8A%A1%E5%99%A8id%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E6%89%80%E5%9C%A8%E8%AF%AD%E9%9F%B3%E9%A2%91%E9%81%93)
=> feat(guild): add fetch_joined_channel method

khl/card/module.py
Implemented the invite module type in card message: https://developer.kaiheila.cn/doc/cardmessage#%E6%A8%A1%E5%9D%97
=> feat(card): add invite module type in card

khl/interface.py, khl/role.py
UserCreated 代表是用户创建的角色
BotSpecified 代表机器人加入服务器自动创建的角色
Booster 代表服务器助力的角色
Everyone 代表默认所有人的角色 `@全体成员`
=> feat(Role): add `type` attribute

khl/bot/bot.py, khl/client.py
Implemented bot.py to support catching all messages except system message including text, kmd, image, audio, video, file, card
=> feat(bot): added `on_message` handler to catch all message except sys

example/ex06_add_rule/README.md
add README for exp06
修改提交信息后重新`pull request`
=> docs(example): exp06

khl/api.py, khl/guild.py
不幸的消息
现在kook官方有问题
如果在服务器里看着机器人创建频道分组，你会被崩端
进入机器人创建过分组的服务器，你会加载不出来左边的频道列表
=> feat(guild): create category with create_channel() method

khl/bot/bot.py, khl/command/command.py, khl/command/manager.py, khl/command/parser.py
我这个方法确实有点蠢了
但是除此之外我也想不到什么方法可以避免开发者在使用khl.py时自己手动写Parser来parse User和Channel
Role比较麻烦，因为现在api还不能通过id获取Role，所以暂时搁置（（
=> 添加了User和Channel的指令parser

khl/bot/bot.py
```python
@bot.on_shutdown
async def on_startup(_):
print(123123132)
```
you can use this to do something when bot stop
=> feat(Bot): add `on_shutdown`

khl/receiver.py
添加了try except以实现发生WSServerHandshakeError时自动重连
=> feat(WebsocketReceiver): add _get_gateway() method and _connect_gateway_and_handle_msg() method

khl/command/command.py, khl/command/lexer.py, khl/command/manager.py
截图：
截图中test指令不管四个字母哪个是大写或小写都可以执行，
aaa指令只有三个字母都是小写的时候可以执行
=> 指令支持忽略名称的大小写

khl/task/manager.py
=> feat(task): add scheduler getter

khl/channel.py, khl/guild.py, khl/permission.py
Renewed from: https://github.com/TWT233/khl.py/pull/119
=> feat: add _permission() methods for category

khl/channel.py
在channel里添加了list_users方法，该方法可以列出可以看到该频道的用户
=> feat: add list_user method in channel

khl/client.py
=> 在client中添加了 fetch_category方法

khl/__init__.py, khl/_types.py, khl/guild.py
=> feat: add method to get guild badges

khl/api.py, khl/channel.py, khl/guild.py, khl/user.py
添加了一个方法可以获取正在语音频道里进行语音的用户
与 #176 有区别，并不是同一个功能
顺带一提这个api不知道什么时候加的反正没写在更新日志里
https://developer.kookapp.cn/doc/http/channel#%E8%AF%AD%E9%9F%B3%E9%A2%91%E9%81%93%E7%94%A8%E6%88%B7%E5%88%97%E8%A1%A8
=> feat: method to get users in voice channel

khl/__init__.py, khl/intimacy.py, khl/user.py
=> feat: add _intimacy() method to user

khl/__init__.py
=> fix: imports

khl/guild.py, khl/user.py
在GuildUser类里面添加了set_nickname()方法
=> feat: guild user set_nickname()

khl/_types.py, khl/api.py, khl/channel.py
=> feat(channel): list channel messages

khl/card/element.py, khl/card/module.py
=> 将卡片消息text的默认类型设置为kmd

khl/card/element.py
=> 将button的默认text类型设置为plain-text以避免黑色文字

khl/api.py
=> Add DirectMessage.view()
